"""Build 05_two_lane_mixed.ipynb programmatically."""
import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []

cells.append(nbf.v4.new_markdown_cell(
    "# 05 — Two-lane mixed traffic (heterogeneous)\n\n"
    "Slow (`v_max=2`) and fast (`v_max=5`) vehicles share two lanes. "
    "How does the slow-vehicle fraction `f_slow` degrade throughput, and "
    "how much does lane-changing (`p_chg`) recover? After the sweep, "
    "space-time diagrams show the per-vehicle structure of the flow.\n\n"
    "**Cache convention** — per-seed shape preserved so SD bands can be "
    "regenerated without resimulating."
))

cells.append(nbf.v4.new_code_cell(
    "%load_ext autoreload\n"
    "%autoreload 2\n"
    "\n"
    "import os, time, numpy as np, matplotlib.pyplot as plt\n"
    "from tqdm.auto import tqdm\n"
    "\n"
    "from nasch_two_lane import TwoLaneNaSch, TwoLaneNaSchWithLights\n"
    "from nasch_two_lane_viz import (\n"
    "    record_space_time, plot_space_time_velocity,\n"
    "    plot_space_time_identity, plot_space_time_type, find_lane_changers,\n"
    ")\n"
    "\n"
    "plt.rcParams.update({\n"
    "    'figure.figsize': (8, 5),\n"
    "    'font.size': 12,\n"
    "    'axes.grid': True,\n"
    "    'grid.alpha': 0.3,\n"
    "    'savefig.dpi': 150,\n"
    "    'savefig.bbox': 'tight',\n"
    "})\n"
    "\n"
    "DATA_DIR = '../data'\n"
    "FIGURES_DIR = '../figures'\n"
    "os.makedirs(DATA_DIR, exist_ok=True)\n"
    "os.makedirs(FIGURES_DIR, exist_ok=True)\n"
    "\n"
    "# ─── Global parameters ────────────────────────────────────────────\n"
    "L          = 500\n"
    "V_MAX      = 5\n"
    "V_SLOW     = 2\n"
    "V_FAST     = 5\n"
    "P_RAND     = 0.3\n"
    "P_IN       = 0.4\n"
    "T_WARMUP   = 5000\n"
    "T_MEASURE  = 10000\n"
    "N_SEEDS    = 5\n"
    "SEEDS      = np.arange(N_SEEDS)\n"
    "V_FREE     = V_MAX - P_RAND\n"
    "\n"
    "F_SLOW_GRID = np.array([0.0, 0.1, 0.2, 0.3, 0.5])\n"
    "P_CHG_GRID  = np.array([0.0, 0.1, 0.3, 0.5, 1.0])\n"
    "\n"
    "# Cache convention: per-seed shape preserved.\n"
    "\n"
    "def load_or_compute(path, compute_fn, force=False):\n"
    "    if force or not os.path.exists(path):\n"
    "        result = compute_fn()\n"
    "        np.savez(path, **result)\n"
    "        return result\n"
    "    with np.load(path) as f:\n"
    "        return {k: f[k] for k in f.files}\n"
    "\n"
    "def greenwave_offsets(N, T_cycle, v_free=V_FREE, L_road=L):\n"
    "    s = L_road / (N + 1)\n"
    "    return np.array([int(round((i * s / v_free) % T_cycle))\n"
    "                     for i in range(N)])\n"
))

# ── Sweep section ──
cells.append(nbf.v4.new_markdown_cell(
    "## Sweep — (f_slow, p_chg)\n\n"
    "Open boundary, no lights. Per cell `(f, p)`, run `n_seeds=5` and "
    "record `J_total`, `v_mean_all/fast/slow`, `rho_lane_0/1`. Cache "
    "preserves per-seed shape `(5, 5, 5)` for each metric."
))

cells.append(nbf.v4.new_code_cell(
    "def per_step_metrics(sim, T_meas):\n"
    "    \"\"\"One full measurement window — accumulates per-type velocity\n"
    "    sums and per-lane density samples.\"\"\"\n"
    "    sim.outflow_count = 0\n"
    "    sum_v_all = 0.0\n"
    "    n_v_all = 0\n"
    "    sum_v_fast = 0.0\n"
    "    n_v_fast = 0\n"
    "    sum_v_slow = 0.0\n"
    "    n_v_slow = 0\n"
    "    rho0_acc = 0.0\n"
    "    rho1_acc = 0.0\n"
    "    for _ in range(T_meas):\n"
    "        sim.step(record_flow=True)\n"
    "        mask = sim.road >= 0\n"
    "        if np.any(mask):\n"
    "            sum_v_all += float(np.sum(sim.road[mask]))\n"
    "            n_v_all += int(np.sum(mask))\n"
    "            fast_mask = mask & (sim.v_max_arr == V_FAST)\n"
    "            slow_mask = mask & (sim.v_max_arr == V_SLOW)\n"
    "            sum_v_fast += float(np.sum(sim.road[fast_mask]))\n"
    "            n_v_fast += int(np.sum(fast_mask))\n"
    "            sum_v_slow += float(np.sum(sim.road[slow_mask]))\n"
    "            n_v_slow += int(np.sum(slow_mask))\n"
    "        rho0_acc += float(np.sum(sim.road[0] >= 0)) / sim.L\n"
    "        rho1_acc += float(np.sum(sim.road[1] >= 0)) / sim.L\n"
    "    return dict(\n"
    "        J_total=sim.outflow_count / T_meas,\n"
    "        v_mean_all=sum_v_all / max(n_v_all, 1),\n"
    "        v_mean_fast=sum_v_fast / max(n_v_fast, 1),\n"
    "        v_mean_slow=sum_v_slow / max(n_v_slow, 1),\n"
    "        rho_lane_0=rho0_acc / T_meas,\n"
    "        rho_lane_1=rho1_acc / T_meas,\n"
    "    )\n"
    "\n"
    "def compute_mixed_sweep():\n"
    "    nf, nc, ns = len(F_SLOW_GRID), len(P_CHG_GRID), N_SEEDS\n"
    "    metrics_keys = ('J_total', 'v_mean_all', 'v_mean_fast', 'v_mean_slow',\n"
    "                    'rho_lane_0', 'rho_lane_1')\n"
    "    out = {k: np.zeros((nf, nc, ns)) for k in metrics_keys}\n"
    "    t0 = time.time()\n"
    "    for fi, f_slow in enumerate(tqdm(F_SLOW_GRID, desc='f_slow')):\n"
    "        for ci, p_chg in enumerate(P_CHG_GRID):\n"
    "            for si, seed in enumerate(SEEDS):\n"
    "                np.random.seed(int(seed))\n"
    "                sim = TwoLaneNaSch(\n"
    "                    L=L, n_lanes=2, v_max=V_MAX, p_rand=P_RAND,\n"
    "                    p_chg=float(p_chg), boundary='open', p_in=P_IN,\n"
    "                    v_max_slow=V_SLOW, v_max_fast=V_FAST,\n"
    "                    f_slow=float(f_slow),\n"
    "                )\n"
    "                sim.warmup(T_WARMUP)\n"
    "                m = per_step_metrics(sim, T_MEASURE)\n"
    "                for k in metrics_keys:\n"
    "                    out[k][fi, ci, si] = m[k]\n"
    "    out.update(\n"
    "        f_slow_grid=F_SLOW_GRID, p_chg_grid=P_CHG_GRID, seeds=SEEDS,\n"
    "        v_max=V_MAX, v_slow=V_SLOW, v_fast=V_FAST, p_rand=P_RAND,\n"
    "        p_in=P_IN, L=L, T_warmup=T_WARMUP, T_measure=T_MEASURE,\n"
    "        wall_clock=time.time() - t0,\n"
    "    )\n"
    "    return out\n"
    "\n"
    "S = load_or_compute(f'{DATA_DIR}/05_two_lane_mixed.npz', compute_mixed_sweep)\n"
    "print(f'wall-clock: {float(S[\"wall_clock\"]):.1f} s')\n"
))

cells.append(nbf.v4.new_code_cell(
    "# Figure 05.A — J vs f_slow, one curve per p_chg.\n"
    "fig, ax = plt.subplots()\n"
    "for ci, p_chg in enumerate(P_CHG_GRID):\n"
    "    m = S['J_total'][:, ci, :].mean(axis=-1)\n"
    "    s = S['J_total'][:, ci, :].std(axis=-1)\n"
    "    ax.plot(F_SLOW_GRID, m, '-o', label=f'p_chg={p_chg:.2f}')\n"
    "    ax.fill_between(F_SLOW_GRID, m - s, m + s, alpha=0.15)\n"
    "ax.axhline(S['J_total'][0, 0, :].mean(), color='k', linestyle='--',\n"
    "            alpha=0.5, label='f_slow=0 baseline')\n"
    "ax.set_xlabel('f_slow')\n"
    "ax.set_ylabel('J_total (cars / timestep)')\n"
    "ax.set_title('05.A — Throughput vs slow-vehicle fraction')\n"
    "ax.legend()\n"
    "fig.savefig(f'{FIGURES_DIR}/05_J_vs_fslow.png')\n"
    "plt.show()\n"
))

cells.append(nbf.v4.new_code_cell(
    "# Figure 05.B — Recovery fraction R(f, p) vs p_chg.\n"
    "# R = (J(f, p) - J(f, 0)) / (J(0, ·) - J(f, 0))\n"
    "# J(0, ·) is taken as the mean baseline at f_slow=0 (any p_chg works since\n"
    "# lane-change is a no-op when both types are identical — pick p_chg=0).\n"
    "J = S['J_total']\n"
    "J_0 = J[0, 0, :].mean()  # f_slow=0, p_chg=0\n"
    "fig, ax = plt.subplots()\n"
    "for fi, f_slow in enumerate(F_SLOW_GRID):\n"
    "    if f_slow == 0:\n"
    "        continue\n"
    "    J_f0 = J[fi, 0, :].mean()  # no lane-change baseline at this f_slow\n"
    "    if J_0 - J_f0 < 1e-6:\n"
    "        continue\n"
    "    R = (J[fi, :, :].mean(axis=-1) - J_f0) / (J_0 - J_f0)\n"
    "    ax.plot(P_CHG_GRID, R, '-o', label=f'f_slow={f_slow:.2f}')\n"
    "ax.axhline(0, color='k', alpha=0.3)\n"
    "ax.axhline(1, color='k', linestyle=':', alpha=0.3, label='full recovery')\n"
    "ax.set_xlabel('p_chg')\n"
    "ax.set_ylabel('Recovery fraction R')\n"
    "ax.set_title('05.B — Recovery fraction vs lane-change rate')\n"
    "ax.legend()\n"
    "fig.savefig(f'{FIGURES_DIR}/05_recovery_fraction.png')\n"
    "plt.show()\n"
))

cells.append(nbf.v4.new_code_cell(
    "# Figure 05.C — v_mean_fast and v_mean_slow vs p_chg at f_slow=0.3.\n"
    "fi = int(np.where(F_SLOW_GRID == 0.3)[0][0])\n"
    "fig, ax = plt.subplots()\n"
    "ax.plot(P_CHG_GRID, S['v_mean_fast'][fi].mean(axis=-1),\n"
    "         '-o', color='C0', label='fast')\n"
    "ax.plot(P_CHG_GRID, S['v_mean_slow'][fi].mean(axis=-1),\n"
    "         '-s', color='C3', label='slow')\n"
    "ax.fill_between(P_CHG_GRID,\n"
    "                 S['v_mean_fast'][fi].mean(axis=-1) - S['v_mean_fast'][fi].std(axis=-1),\n"
    "                 S['v_mean_fast'][fi].mean(axis=-1) + S['v_mean_fast'][fi].std(axis=-1),\n"
    "                 alpha=0.15, color='C0')\n"
    "ax.fill_between(P_CHG_GRID,\n"
    "                 S['v_mean_slow'][fi].mean(axis=-1) - S['v_mean_slow'][fi].std(axis=-1),\n"
    "                 S['v_mean_slow'][fi].mean(axis=-1) + S['v_mean_slow'][fi].std(axis=-1),\n"
    "                 alpha=0.15, color='C3')\n"
    "ax.axhline(V_FAST, color='C0', linestyle=':', alpha=0.5)\n"
    "ax.axhline(V_SLOW, color='C3', linestyle=':', alpha=0.5)\n"
    "ax.set_xlabel('p_chg')\n"
    "ax.set_ylabel('Mean velocity')\n"
    "ax.set_title(f'05.C — Per-type velocity at f_slow={F_SLOW_GRID[fi]:.2f}')\n"
    "ax.legend()\n"
    "fig.savefig(f'{FIGURES_DIR}/05_velocity_by_type.png')\n"
    "plt.show()\n"
))

# ── Space-time section ──
cells.append(nbf.v4.new_markdown_cell(
    "## Space-time diagrams — heterogeneous traffic\n\n"
    "Four scenarios at `f_slow = 0.3`, recorded at `L=200, T_record=200, "
    "T_warmup=1000, seed=12345`:\n\n"
    "* **A**: no lights, `p_chg = 0.0`\n"
    "* **B**: no lights, `p_chg = 0.5`\n"
    "* **C**: with lights (greenwave), `p_chg = 0.0`\n"
    "* **D**: with lights, `p_chg = 0.5`\n\n"
    "Each scenario is rendered three ways (velocity, identity, type). "
    "Identity plots in B and D highlight cars that actually changed lanes "
    "during the recording window so a few example trajectories can be traced."
))

cells.append(nbf.v4.new_code_cell(
    "ST_L = 200\n"
    "ST_T_RECORD = 200\n"
    "ST_T_WARMUP = 1000\n"
    "ST_SEED = 12345\n"
    "ST_F_SLOW = 0.3\n"
    "\n"
    "# Light config for scenarios C, D — small N to fit in L=200.\n"
    "ST_N = 2\n"
    "ST_T_CYCLE = 60\n"
    "ST_T_GREEN = 30\n"
    "ST_PHI = greenwave_offsets(ST_N, ST_T_CYCLE, v_free=V_FREE, L_road=ST_L)\n"
    "\n"
    "def make_sim(*, with_lights, p_chg, seed):\n"
    "    np.random.seed(seed)\n"
    "    if with_lights:\n"
    "        return TwoLaneNaSchWithLights(\n"
    "            L=ST_L, n_lanes=2, v_max=V_MAX, p_rand=P_RAND, p_chg=p_chg,\n"
    "            boundary='open', p_in=P_IN,\n"
    "            v_max_slow=V_SLOW, v_max_fast=V_FAST, f_slow=ST_F_SLOW,\n"
    "            N=ST_N, T_cycle=ST_T_CYCLE, T_green=ST_T_GREEN,\n"
    "            phase_offsets=ST_PHI,\n"
    "        )\n"
    "    return TwoLaneNaSch(\n"
    "        L=ST_L, n_lanes=2, v_max=V_MAX, p_rand=P_RAND, p_chg=p_chg,\n"
    "        boundary='open', p_in=P_IN,\n"
    "        v_max_slow=V_SLOW, v_max_fast=V_FAST, f_slow=ST_F_SLOW,\n"
    "    )\n"
    "\n"
    "scenarios = {\n"
    "    'A': dict(with_lights=False, p_chg=0.0),\n"
    "    'B': dict(with_lights=False, p_chg=0.5),\n"
    "    'C': dict(with_lights=True,  p_chg=0.0),\n"
    "    'D': dict(with_lights=True,  p_chg=0.5),\n"
    "}\n"
    "histories = {}\n"
    "for label, cfg in scenarios.items():\n"
    "    sim = make_sim(seed=ST_SEED, **cfg)\n"
    "    histories[label] = record_space_time(sim, T_record=ST_T_RECORD,\n"
    "                                          T_warmup=ST_T_WARMUP)\n"
    "    print(f\"{label}: cars seen = {(histories[label]['car_id_history'] >= 0).any(axis=(1,2)).sum()}\")\n"
))

cells.append(nbf.v4.new_code_cell(
    "# Stack two scenarios side-by-side (or stacked) into a single figure\n"
    "# per (colouring × light-condition). Each scenario contributes both lanes,\n"
    "# so figure is 4 rows × 1 col (A/B lane0, A/B lane1, etc.).\n"
    "from matplotlib.gridspec import GridSpec\n"
    "from matplotlib.colors import ListedColormap, BoundaryNorm\n"
    "from matplotlib.patches import Patch\n"
    "\n"
    "def lane_panel_grid(scenario_keys, colouring, history_set, savepath, suptitle):\n"
    "    n_scen = len(scenario_keys)\n"
    "    fig, axes = plt.subplots(n_scen * 2, 1, figsize=(11, 3 * n_scen * 2),\n"
    "                              sharex=True, constrained_layout=True)\n"
    "    if colouring == 'velocity':\n"
    "        cmap = plt.get_cmap('RdYlGn').copy()\n"
    "        cmap.set_bad('white')\n"
    "    elif colouring == 'type':\n"
    "        cmap = ListedColormap(['white', '#1f77b4', '#d62728'])\n"
    "        norm = BoundaryNorm([-0.5, 0.5, 1.5, 2.5], cmap.N)\n"
    "    last_im = None\n"
    "    for si, label in enumerate(scenario_keys):\n"
    "        h = history_set[label]\n"
    "        T = h['velocity_history'].shape[0]\n"
    "        for lane in (0, 1):\n"
    "            ax = axes[si * 2 + lane]\n"
    "            if colouring == 'velocity':\n"
    "                v = h['velocity_history'][:, lane, :].astype(float)\n"
    "                vm = h['v_max_history'][:, lane, :].astype(float)\n"
    "                with np.errstate(divide='ignore', invalid='ignore'):\n"
    "                    norm_arr = np.where(vm > 0, v / np.maximum(vm, 1), np.nan)\n"
    "                norm_arr = np.where(h['velocity_history'][:, lane, :] < 0, np.nan, norm_arr)\n"
    "                masked = np.ma.masked_invalid(norm_arr)\n"
    "                last_im = ax.imshow(masked, aspect='auto', origin='upper',\n"
    "                                     extent=[0, ST_L, T, 0], cmap=cmap,\n"
    "                                     vmin=0, vmax=1, interpolation='nearest')\n"
    "            elif colouring == 'identity':\n"
    "                ids = h['car_id_history'][:, lane, :]\n"
    "                rgba = np.ones(ids.shape + (4,))\n"
    "                rgba[..., 3] = 0.0\n"
    "                car_mask = ids >= 0\n"
    "                base_cmap = plt.get_cmap('tab20')\n"
    "                colours = base_cmap((ids % 20) / 19)\n"
    "                rgba[car_mask] = colours[car_mask]\n"
    "                # Highlight lane-changers in B and D\n"
    "                if label in ('B', 'D'):\n"
    "                    hl = set(find_lane_changers(h['car_id_history'], max_ids=5))\n"
    "                    if hl:\n"
    "                        hl_arr = np.isin(ids, list(hl))\n"
    "                        non_hl = car_mask & ~hl_arr\n"
    "                        rgba[non_hl] = (0.85, 0.85, 0.85, 0.5)\n"
    "                ax.imshow(rgba, aspect='auto', origin='upper',\n"
    "                           extent=[0, ST_L, T, 0], interpolation='nearest')\n"
    "            elif colouring == 'type':\n"
    "                vm = h['v_max_history'][:, lane, :]\n"
    "                coded = np.zeros_like(vm)\n"
    "                coded[vm == V_FAST] = 1\n"
    "                coded[vm == V_SLOW] = 2\n"
    "                ax.imshow(coded, aspect='auto', origin='upper',\n"
    "                           extent=[0, ST_L, T, 0], cmap=cmap, norm=norm,\n"
    "                           interpolation='nearest')\n"
    "            ax.set_title(f'Scenario {label} — Lane {lane}', fontsize=10)\n"
    "            ax.set_ylabel('Time')\n"
    "            # Light overlay if present\n"
    "            if 'light_state_history' in h:\n"
    "                for li, pos in enumerate(h['light_pos']):\n"
    "                    col = h['light_state_history'][:, li]\n"
    "                    starts = [0] + [k for k in range(1, len(col))\n"
    "                                    if col[k] != col[k-1]] + [len(col)]\n"
    "                    for k in range(len(starts) - 1):\n"
    "                        s, e = starts[k], starts[k+1]\n"
    "                        ax.fill_betweenx([s, e], pos - 0.4, pos + 0.4,\n"
    "                                         color='red' if col[s] else 'green',\n"
    "                                         alpha=0.4, linewidth=0)\n"
    "    axes[-1].set_xlabel('Cell position')\n"
    "    if colouring == 'velocity':\n"
    "        fig.colorbar(last_im, ax=axes, shrink=0.5, label='v / v_max^(i)')\n"
    "    elif colouring == 'type':\n"
    "        fig.legend(handles=[Patch(facecolor='#1f77b4', label=f'fast (v={V_FAST})'),\n"
    "                             Patch(facecolor='#d62728', label=f'slow (v={V_SLOW})')],\n"
    "                    loc='upper right', fontsize=9)\n"
    "    fig.suptitle(suptitle, fontsize=12)\n"
    "    fig.savefig(savepath)\n"
    "    plt.show()\n"
    "\n"
    "for colouring in ('velocity', 'identity', 'type'):\n"
    "    lane_panel_grid(['A', 'B'], colouring, histories,\n"
    "                     f'{FIGURES_DIR}/05_st_{colouring}_no_lights.png',\n"
    "                     f'No-lights: A (p_chg=0) | B (p_chg=0.5), '\n"
    "                     f'f_slow={ST_F_SLOW}, {colouring} colouring')\n"
    "    lane_panel_grid(['C', 'D'], colouring, histories,\n"
    "                     f'{FIGURES_DIR}/05_st_{colouring}_with_lights.png',\n"
    "                     f'With lights: C (p_chg=0) | D (p_chg=0.5), '\n"
    "                     f'f_slow={ST_F_SLOW}, {colouring} colouring')\n"
))

cells.append(nbf.v4.new_markdown_cell(
    "## Summary\n\n"
    "Slow vehicles drag flow down monotonically with `f_slow`. Lane-changing "
    "partially recovers the loss; the recovery fraction (Figure 05.B) is "
    "highest at intermediate `f_slow` and saturates by `p_chg ≈ 0.3`. The "
    "space-time figures show why: at `p_chg=0` slow cars lock down both "
    "lanes (visible as platoons of trapped fast cars). With `p_chg=0.5`, "
    "fast cars route around slow ones — visible as identity-coloured "
    "diagonal traces switching panels."
))

nb.cells = cells
nb.metadata = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.11"},
}

import sys
out = sys.argv[1] if len(sys.argv) > 1 else "05_two_lane_mixed.ipynb"
with open(out, "w", encoding="utf-8") as f:
    nbf.write(nb, f)
print(f"wrote {out} ({len(cells)} cells)")
